// The complete set of icons a category can carry.
//
// Category icons are auto-assigned from the keyword table in
// category-icon-picker.ts, so the set is small and known at build time.
// Rendering them through <DynamicIcon> from "lucide-react/dynamic" instead
// shipped that entry point's ~2,000-icon import registry (~24 KB gzipped) to
// every visitor of every grid page, then fetched each icon as its own chunk
// after hydration, so icons popped in late. Named imports are tree-shaken to
// just the icons below, and render server-side with no client cost.
//
// The picker validates its output against CATEGORY_ICON_NAMES, so a category
// can never be stored with an icon missing from this map.

import {
  Bike,
  BookOpen,
  Bug,
  Building2,
  Cake,
  Calculator,
  Camera,
  Car,
  CarFront,
  Dog,
  Drama,
  Dumbbell,
  Flame,
  Flower,
  Flower2,
  GraduationCap,
  Hammer,
  HardHat,
  Home,
  KeyRound,
  Laptop,
  Music,
  Paintbrush,
  PartyPopper,
  Pill,
  Plane,
  Printer,
  Scale,
  Scissors,
  Shield,
  ShieldCheck,
  Shirt,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  Stethoscope,
  Store,
  Syringe,
  Truck,
  Utensils,
  UtensilsCrossed,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "bike": Bike,
  "book-open": BookOpen,
  "bug": Bug,
  "building-2": Building2,
  "cake": Cake,
  "calculator": Calculator,
  "camera": Camera,
  "car": Car,
  "car-front": CarFront,
  "dog": Dog,
  "drama": Drama,
  "dumbbell": Dumbbell,
  "flame": Flame,
  "flower": Flower,
  "flower-2": Flower2,
  "graduation-cap": GraduationCap,
  "hammer": Hammer,
  "hard-hat": HardHat,
  "home": Home,
  "key-round": KeyRound,
  "laptop": Laptop,
  "music": Music,
  "paintbrush": Paintbrush,
  "party-popper": PartyPopper,
  "pill": Pill,
  "plane": Plane,
  "printer": Printer,
  "scale": Scale,
  "scissors": Scissors,
  "shield": Shield,
  "shield-check": ShieldCheck,
  "shirt": Shirt,
  "shopping-cart": ShoppingCart,
  "smartphone": Smartphone,
  "smile": Smile,
  "sparkles": Sparkles,
  "stethoscope": Stethoscope,
  "syringe": Syringe,
  "truck": Truck,
  "utensils": Utensils,
  "utensils-crossed": UtensilsCrossed,
  "wrench": Wrench,
  "zap": Zap,
  "store": Store,
};

export const CATEGORY_ICON_NAMES = new Set(Object.keys(CATEGORY_ICONS));
