// In-memory seed used when Supabase env vars are absent. Same shape as the DB.

type Row = Record<string, unknown>;

const cities: Row[] = [
  { id: "c1", name: "Lucknow", slug: "lucknow", active: true },
];

const neighborhoods: Row[] = [
  { id: "n1", city_id: "c1", name: "Gomti Nagar", slug: "gomti-nagar" },
  { id: "n2", city_id: "c1", name: "Hazratganj", slug: "hazratganj" },
  { id: "n3", city_id: "c1", name: "Aliganj", slug: "aliganj" },
  { id: "n4", city_id: "c1", name: "Indira Nagar", slug: "indira-nagar" },
  { id: "n5", city_id: "c1", name: "Alambagh", slug: "alambagh" },
];

// Tiffin has a starter fields_schema so /admin/categories has something to
// show in demo mode.
const tiffinFields = [
  {
    key: "diet",
    label: "Diet",
    type: "select",
    options: ["Veg", "Non-veg", "Jain", "Both"],
  },
  { key: "price_per_meal", label: "₹ per meal", type: "number" },
  { key: "delivery", label: "Home delivery", type: "boolean" },
];

const categories: Row[] = [
  { id: "k1", name: "Tiffin Services", slug: "tiffin-services", icon: "🍱", fields_schema: tiffinFields },
  { id: "k2", name: "Home Cleaning", slug: "home-cleaning", icon: "🧹", fields_schema: null },
  { id: "k3", name: "Tailors", slug: "tailors", icon: "🧵", fields_schema: null },
  { id: "k4", name: "Electricians", slug: "electricians", icon: "⚡", fields_schema: null },
  { id: "k5", name: "Plumbers", slug: "plumbers", icon: "🔧", fields_schema: null },
  { id: "k6", name: "Tuition & Coaching", slug: "tuition-coaching", icon: "📚", fields_schema: null },
  { id: "k7", name: "Car & Bike Repair", slug: "car-bike-repair", icon: "🔩", fields_schema: null },
  { id: "k8", name: "Salons", slug: "salons", icon: "💇", fields_schema: null },
];

// Unsplash source images (free, cached).
const IMG_TIFFIN_1 =
  "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&auto=format&fit=crop";
const IMG_TIFFIN_2 =
  "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&auto=format&fit=crop";

const listings: Row[] = [
  {
    id: "l1",
    name: "Anita's Home Kitchen",
    slug: "anitas-home-kitchen",
    category_id: "k1",
    neighborhood_id: "n1",
    description: "Home-cooked North Indian tiffin. Monthly plans, breakfast + dinner. Jain options.",
    whatsapp_number: "+919812345678",
    hours_json: {
      mon: { open: "07:00", close: "22:00" },
      tue: { open: "07:00", close: "22:00" },
      wed: { open: "07:00", close: "22:00" },
      thu: { open: "07:00", close: "22:00" },
      fri: { open: "07:00", close: "22:00" },
      sat: { open: "07:00", close: "22:00" },
      sun: null,
    },
    photo_url: IMG_TIFFIN_1,
    verified: true,
    verified_at: "2026-07-14T10:30:00Z",
    pin_code: "226010",
    whatsapp_clicks: 12,
    fields_values: { diet: "Both", price_per_meal: 110, delivery: true },
    status: "approved",
    categories: { name: "Tiffin Services", slug: "tiffin-services" },
    neighborhoods: { name: "Gomti Nagar", slug: "gomti-nagar", city_id: "c1" },
  },
  {
    id: "l2",
    name: "Rasoi Ghar Tiffin",
    slug: "rasoi-ghar-tiffin",
    category_id: "k1",
    neighborhood_id: "n2",
    description: "Ghar ka khaana. Roti-sabzi-dal-chawal, ₹90/meal. Delivers Hazratganj + nearby.",
    whatsapp_number: "+919811111111",
    hours_json: {
      mon: { open: "11:00", close: "22:00" },
      tue: { open: "11:00", close: "22:00" },
      wed: { open: "11:00", close: "22:00" },
      thu: { open: "11:00", close: "22:00" },
      fri: { open: "11:00", close: "22:00" },
      sat: { open: "11:00", close: "22:00" },
      sun: { open: "11:00", close: "22:00" },
    },
    photo_url: IMG_TIFFIN_2,
    verified: true,
    verified_at: "2026-06-02T09:15:00Z",
    pin_code: "226001",
    whatsapp_clicks: 8,
    fields_values: { diet: "Veg", price_per_meal: 90, delivery: true },
    status: "approved",
    categories: { name: "Tiffin Services", slug: "tiffin-services" },
    neighborhoods: { name: "Hazratganj", slug: "hazratganj", city_id: "c1" },
  },
  {
    id: "l3",
    name: "Maa Tiffin Service",
    slug: "maa-tiffin-service",
    category_id: "k1",
    neighborhood_id: "n3",
    description: "Simple UP-style home food. Monthly student packages.",
    whatsapp_number: "+919822222222",
    hours_json: null,
    photo_url: null,
    verified: false,
    pin_code: "226024",
    whatsapp_clicks: 3,
    fields_values: { diet: "Veg", price_per_meal: 75, delivery: false },
    status: "approved",
    categories: { name: "Tiffin Services", slug: "tiffin-services" },
    neighborhoods: { name: "Aliganj", slug: "aliganj", city_id: "c1" },
  },
  {
    id: "l4",
    name: "Shivani's Kitchen",
    slug: "shivanis-kitchen",
    category_id: "k1",
    neighborhood_id: "n4",
    description: "Bengali + North Indian. Weekly menu on WhatsApp. Trial meal available.",
    whatsapp_number: "+919833333333",
    hours_json: null,
    photo_url: null,
    verified: true,
    verified_at: "2026-08-03T16:45:00Z",
    pin_code: "226016",
    whatsapp_clicks: 21,
    fields_values: { diet: "Non-veg", price_per_meal: 130, delivery: true },
    status: "approved",
    categories: { name: "Tiffin Services", slug: "tiffin-services" },
    neighborhoods: { name: "Indira Nagar", slug: "indira-nagar", city_id: "c1" },
  },
  {
    id: "l5",
    name: "Annapurna Tiffin",
    slug: "annapurna-tiffin",
    category_id: "k1",
    neighborhood_id: "n5",
    description: "Working professionals + hostels. Same-price veg/non-veg thali.",
    whatsapp_number: "+919844444444",
    hours_json: null,
    photo_url: null,
    verified: false,
    pin_code: "226005",
    whatsapp_clicks: 5,
    fields_values: null,
    status: "approved",
    categories: { name: "Tiffin Services", slug: "tiffin-services" },
    neighborhoods: { name: "Alambagh", slug: "alambagh", city_id: "c1" },
  },
];

export const MOCK_TABLES: Record<string, Row[]> = {
  cities,
  neighborhoods,
  categories,
  listings,
  admin_users: [{ user_id: "demo-admin", created_at: "2026-08-01T00:00:00Z" }],
  listing_reports: [],
  analytics_events: [],
  search_events: [
    { id: "s1", query: "biryani", matched_count: 0, city_slug: "lucknow", pin_code: null, created_at: "2026-08-24T12:00:00Z" },
    { id: "s2", query: "gym trainer", matched_count: 0, city_slug: "lucknow", pin_code: null, created_at: "2026-08-24T14:00:00Z" },
    { id: "s3", query: "carpenter", matched_count: 0, city_slug: "lucknow", pin_code: null, created_at: "2026-08-25T09:00:00Z" },
    { id: "s4", query: "biryani", matched_count: 0, city_slug: "lucknow", pin_code: null, created_at: "2026-08-25T18:00:00Z" },
    { id: "s5", query: "chai", matched_count: 0, city_slug: "lucknow", pin_code: null, created_at: "2026-08-26T09:00:00Z" },
    { id: "s6", query: "biryani", matched_count: 0, city_slug: "lucknow", pin_code: null, created_at: "2026-08-26T11:00:00Z" },
  ],
  outreach_leads: [
    {
      id: "o1",
      business_name: "Sharma Ji Ka Tiffin",
      whatsapp_number: "+919855555555",
      category_id: "k1",
      neighborhood_id: "n2",
      source_note: "seen on Google Maps, 4.6★",
      status: "lead",
      contacted_at: null,
      replied_at: null,
      listing_id: null,
      created_at: "2026-08-20T09:00:00Z",
      categories: { id: "k1", slug: "tiffin-services", name: "Tiffin Services" },
      neighborhoods: { id: "n2", slug: "hazratganj", name: "Hazratganj" },
    },
    {
      id: "o2",
      business_name: "Rekha Home Foods",
      whatsapp_number: "+919866666666",
      category_id: "k1",
      neighborhood_id: "n1",
      source_note: "referred by neighbor",
      status: "contacted",
      contacted_at: "2026-08-21T14:00:00Z",
      replied_at: null,
      listing_id: null,
      created_at: "2026-08-19T10:00:00Z",
      categories: { id: "k1", slug: "tiffin-services", name: "Tiffin Services" },
      neighborhoods: { id: "n1", slug: "gomti-nagar", name: "Gomti Nagar" },
    },
    {
      id: "o3",
      business_name: "Green Bowl Tiffin",
      whatsapp_number: "+919877777777",
      category_id: "k1",
      neighborhood_id: "n4",
      source_note: "Justdial listing, verified working number",
      status: "no_response",
      contacted_at: "2026-08-18T11:00:00Z",
      replied_at: null,
      listing_id: null,
      created_at: "2026-08-17T09:00:00Z",
      categories: { id: "k1", slug: "tiffin-services", name: "Tiffin Services" },
      neighborhoods: { id: "n4", slug: "indira-nagar", name: "Indira Nagar" },
    },
  ],
};
